# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: whatsthestoryabout
email: whatsthestoryabout@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal dedicated blog to share and discuss storytelling
baseurl: "/wtsa" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
instagram_username: whatsthestoryabout
github_username:  chuangcaleb

show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-wikilinks
  - jekyll-sitemap
  - jekyll-last-modified-at 
  - jekyll-titles-from-headings

collections:
  poosts:
    output: true
  paages:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# * DATA --------------------------------------------------------------------

header_pages:
  - _paages/about.md
  - _paages/browse.md

# * DEFAULTS -------------------------------------------------------------------

defaults:
  - scope:
      path: ""
      type: paages
    values:
      excerpt_separator: <!--more-->
  - scope:
      path: ""
      type: poosts
    values:
      layout: post
      permalink: posts/:title
      excerpt_separator: <!--more-->
      toc: true
  - scope:
      path: ""
      type: paages
    values:
      layout: page
      permalink: :title
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "assets/img"
    values: 
      image: true

# * PLUGINS --------------------------------------------------------------------

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

wikilinks:
  attributes:
    enabled: true
  css:
  enabled: true
  exclude: []

# last-modified-at:
#     date-format: '%d %b %Y'